### ISSUE TITLE
Disable start/end hidden view.

### ISSUE THREAD

**Issue by IonutNegru87** [alex-townsend/SwipeOpenItemTouchHelper#12]
Hello,

I have a scenario where I only need to swipe from the end (right to left swipe).
Everything works fine, except that I'm also allowed to swipe from the start (left to right swipe). Is there an property or an method I can use to disable this behavior? Or can you implement an feature like this? 

I'm thinking this can be implemented rather easily because you will only have to verify if the getStartHiddenViewSize() and getEndHiddenViewSize() returned something bigger than 0 (to actually have an valid hidden view).

Thank you.

**Comment by alex-townsend** [comment]
Having getStartHiddenViewSize() or getEndHiddenViewSize() returning 0 will always have the swipe return to the close position when you swipe in that direction, or are you asking for it not to be possible to go past 0 translation in the direction that shouldn't support swipe?

**Comment by IonutNegru87** [comment]
Hello @alex-townsend,

I'm referring to the second option. Where the swipe is disabled completely if the size of hidden view is 0, not getting past 0 translation in that direction.

**Comment by alex-townsend** [comment]
I think that's a reasonable request. I'll add a flag that can be set for enabling this functionality. In the mean time, if you need it right now, you can get this behavior by implementing your own SwipeOpenItemTouchHelper.Callback class and override onChildDraw. Hopefully I'll be able to get to this sometime this week though.

**Comment by alex-townsend** [comment]
Merged in #18 -- should have the added for preventing translation of zero-sized views.

**Comment by alex-townsend** [comment]
Closing this out, if you have any issues with the new functionality or more suggestions, please feel free to open another issue.
