### ISSUE TITLE
add close() on SwipeOpenItemTouchHelper

### ISSUE THREAD

**Issue by muigukenneth** [alex-townsend/SwipeOpenItemTouchHelper#15]
closing the SwipeOpenViewholder programmatically would be a great enhancement in a scenario where i click on the hidden view and an action is performed and then restore to the normal state instead of having to close using the gestures.

**Comment by alex-townsend** [comment]
I'll try to get to this sometime this week -- good suggestion.

**Comment by alex-townsend** [comment]
Merged in the changes for closing a given position or closing all positions, can get it from a snapshot build right now, or I'll get it in another release soon.

**Comment by muigukenneth** [comment]
Thanks Alex ,i will wait for the release version for testing, any idea when you are releasing the next version?

**Comment by alex-townsend** [comment]
@muigukenneth will hopefully get to it tomorrow -- I'm at I/O this week so I have been busy.

**Comment by alex-townsend** [comment]
Released in 1.2.0, closing this.
