### ISSUE TITLE
Force to use two layouts to achieve selector for full raw.

### ISSUE THREAD

**Issue by ar-g** [alex-townsend/SwipeOpenItemTouchHelper#25]
This what I usually ended up in my item layouts because need extra background. 

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    >

  <include layout="@layout/container_swipe_to_delete"/>

  <LinearLayout
      android:id="@+id/content_view"
      android:orientation="horizontal"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:minHeight="45dp"
      android:gravity="center_vertical"
      android:background="@color/gray_dark"
      android:clickable="true"
      >
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center_vertical"
        android:background="?attr/selectableItemBackground"
        >...
```

Am I missing smth? Solution might be custom selector, though, but without app_compat

**Comment by alex-townsend** [comment]
Which view are you using for the swipe view? I don't see a need for the LinearLayout inside content_view.

**Comment by alex-townsend** [comment]
If all you're looking for is a selectable background where the color is gray_dark, then you should be using a [StateListDrawable](https://developer.android.com/reference/android/graphics/drawable/StateListDrawable.html)

**Comment by ar-g** [comment]
I need to have an additional layout with a background to hide swipe_view. With the only selector, swipe_view will be visible.

StateListDrawable is a good option, but don't give a possibility to use default AppCompat selectors which look differently across platforms

**Comment by alex-townsend** [comment]
Think you're either going to need to create a custom StateListDrawable or do the wrapping like you are in this case then. You'd only need to create 2 custom StateListDrawables (one w/ ripple for API 21+ and one w/o ripple for API < 21)

**Comment by ar-g** [comment]
Yes, you are right, thanks. Probably, need to close this issue.

**Comment by alex-townsend** [comment]
Closing this out. Something to note, in the upcoming 24.0 version of AppCompat, using theme attribute values in StateListDrawables will be possible, so you might want to keep an eye on that.
