### ISSUE TITLE
How to integrate with drag and drop?

### ISSUE THREAD

**Issue by ar-g** [alex-townsend/SwipeOpenItemTouchHelper#26]
I'm trying to add drag and drop functionality adding another ItemTouchHelper like in this [post](https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-b9456d2b1aaf)

But I stumbled upon an issue that sometimes it's not working. 
1. Need to click twice to get clickListener called.
2. Click listener never gets called at all.

I have an assumption that it might be because clearView in ItemTouchHelper callback but not sure.

Is there is any recommendations how to integrate this library with drag and drop?

**Comment by ar-g** [comment]
Pretty interesting but changing the order of these helpers, fixed this issue

``` java
ItemTouchHelper.Callback callback = new DragAndDroupTouchHelperCallback(adapter);
ItemTouchHelper touchHelper = new ItemTouchHelper(callback);
touchHelper.attachToRecyclerView(rvRoute);


final SwipeOpenItemTouchHelper.SimpleCallback simpleCallback = new SwipeOpenItemTouchHelper.SimpleCallback(SwipeOpenItemTouchHelper.START | SwipeOpenItemTouchHelper.END);
SwipeOpenItemTouchHelper helper = new SwipeOpenItemTouchHelper(simpleCallback);
helper.setPreventZeroSizeViewSwipes(true);
helper.attachToRecyclerView(rvRoute);
```

**Comment by alex-townsend** [comment]
Good to know that it works alongside the drag feature from ItemTouchHelper. Adding the drag functionality back in might be something to do in the future (it was taken out for the initial implementation that lead to me making this library).

**Comment by alex-townsend** [comment]
Going to close this out since it's possible to user the ItemTouchHelper -- will reopen a new ticket if drag is added back into this library.
