### ISSUE TITLE
How can i mix swipable and not swipable views ?

### ISSUE THREAD

**Issue by yann-h** [alex-townsend/SwipeOpenItemTouchHelper#27]
I have a recyclerview with headers that should not be swipable and content views that are swipable. How can i mix both types of cells in the same recyclerview ? i have an exception in the log because of this line :

throw new IllegalStateException("Swiped View Holders must implement SwipeOpenViewHolder");

Thx for your help,
Yann

**Comment by alex-townsend** [comment]
This is probably something I should change -- to have non-swipe holders just prevent the swipe silently instead of with an exception (dumb idea in hindsight). I'll try to get this change in today.

**Comment by alex-townsend** [comment]
@yann-h start using version 1.2.1 and you should be good to go.

**Comment by alex-townsend** [comment]
Closing as this functionality has been changed with the merge of #28.
