### ISSUE TITLE
OnClickItemRecyclerView

### ISSUE THREAD

**Issue by MansoorJafari** [alex-townsend/SwipeOpenItemTouchHelper#29]
Hi
after use this library onitem click recyclerview like this.
![untitled](https://cloud.githubusercontent.com/assets/15822698/16356271/729170cc-3ae7-11e6-896c-9d9098858f9e.png)

only partial of recycler view has ripple effect.

Please Help. 
Thank You.

**Comment by alex-townsend** [comment]
The ripple effect will be constrained to the view that it is on, so if you swipe open a view, and then click one of the items in the RecyclerView, the ripple will be contained in your clicked view only.

**Comment by MansoorJafari** [comment]
Thank you Mr.alex
