### ISSUE TITLE
 Interference with OnTabItem Recycler

### ISSUE THREAD

**Issue by MansoorJafari** [alex-townsend/SwipeOpenItemTouchHelper#30]
Hi
In my app I'm using RecyclerView addOnItemListener that I use this code
`
import android.content.Context;
import android.support.v7.widget.RecyclerView;
import android.view.GestureDetector;
import android.view.MotionEvent;
import android.view.View;

/**
- Created by MansoorJ on 6/25/2016.
  */
  public class RecyclerViewTouchListener  implements RecyclerView.OnItemTouchListener {
  
  private GestureDetector gestureDetector;
  private ClickListener clickListener;
  
  public RecyclerViewTouchListener(Context context, final RecyclerView recyclerView, final ClickListener clickListener) {
      this.clickListener=clickListener;
      gestureDetector=new GestureDetector(new GestureDetector.SimpleOnGestureListener(){
  
  ```
      @SuppressWarnings("deprecation")
      @Override
      public boolean onSingleTapUp(MotionEvent e) {
          View child = recyclerView.findChildViewUnder(e.getX(), e.getY());
          if (child!=null && clickListener!=null){
              clickListener.OnClick(child,recyclerView.getChildPosition(child));
          }
          return true;
      }
  });
  ```
  
  }
  
  @Override
  public boolean onInterceptTouchEvent(RecyclerView rv, MotionEvent e) {
      View child = rv.findChildViewUnder(e.getX(), e.getY());
      if (child != null && clickListener != null && gestureDetector.onTouchEvent(e)) {
          //noinspection deprecation
          clickListener.OnClick(child, rv.getChildPosition(child));
      }
      return false;
  }
  
  @Override
  public void onTouchEvent(RecyclerView rv, MotionEvent e) {
  
  }
  
  @Override
  public void onRequestDisallowInterceptTouchEvent(boolean disallowIntercept) {
  
  }
  
  public static interface ClickListener {
      void OnClick(View view,int position);
  
  }
  }

`

in my fragment 

`
RecyclerViewTouchListener touchListener=new RecyclerViewTouchListener(getContext(), mRecyclerView, new RecyclerViewTouchListener.ClickListener() {

```
        @Override
        public void OnClick(View view, int position) {
            WordFragment wordfr=WordFragment.newInstance(results.get(position).getGroupId());
            FragmentTransaction transaction=getActivity().getSupportFragmentManager().beginTransaction();
            transaction.replace(R.id.main_fragment,wordfr);
            transaction.commit();
        }

    });
    mRecyclerView.addOnItemTouchListener(touchListener);
```

`

but only work onclick recycler
mean after click edit or delete swipe onclick event worked.

please help.

**Comment by alex-townsend** [comment]
The SwipeOpenItemTouchHelper library uses an RecyclerView.OnItemTouchListener to detect the swipe movements. Adding another OnItemTouchListener to the same RecyclerView could possibly conflict with the library. Since it just looks like you are using the touch listener to register as click event, I would suggest looking into adding a callback between your RecyclerView.Adapter and your Fragment for click events (look at this blog for more info: http://antonioleiva.com/recyclerview-listener/)

**Comment by alex-townsend** [comment]
Closing this out -- let me know if you have any further questions/issues.
