### ISSUE TITLE
Open Programmatically Item

### ISSUE THREAD

**Issue by chemickypes** [alex-townsend/SwipeOpenItemTouchHelper#34]
There is a way to open item programmatically? For example, using item position.

**Comment by alex-townsend** [comment]
Hey, sorry I was on vacation for the holidays. I'll try to get to this sometime within the next week.

**Comment by chemickypes** [comment]
@alex-townsend thank you! I'll wait for this change!

**Comment by alex-townsend** [comment]
Added two new methods *openPositionStart(int)* and *openPositionEnd(int)* to SwipeOpenItemTouchHelper (see #35).

**Comment by chemickypes** [comment]
thanks!
