### ISSUE TITLE
Upgrade SwipeOpenItemTouchHelper to use newer Android support libs?

### ISSUE THREAD

**Issue by DundieWinner** [alex-townsend/SwipeOpenItemTouchHelper#39]
I am working on a project right now where we just upgraded our gradle files to import the latest v26 android support libraries. Unfortunately, this breaks SwipeOpenItemTouchHelper because it currently does not have its own v4 import, and at the same time, files still import android.support.v4.animation.* which does not exist anymore.

Do you have plans to upgrade this libraries methods to be compliant with the newer android support libraries?

**Comment by alex-townsend** [comment]
Sure thing, I'll try to get to that sometime today.

**Comment by DundieWinner** [comment]
Thanks!!

**Comment by alex-townsend** [comment]
@javajared should be available with 1.4.0, which should be up on jitpack in a few minutes.

**Comment by DundieWinner** [comment]
@alex-townsend amazing, thank you very much

**Comment by alex-townsend** [comment]
Closing, please open another issue if you find anything else.
