### ISSUE TITLE
Swipe back

### ISSUE THREAD

**Issue by TooLazyy** [alex-townsend/SwipeOpenItemTouchHelper#42]
Hi. Is there any way to swipe back to a neutral position?
If user swipe left and then swipe right to show original view.
I see now only one solution: return zero size for getStartHiddenViewSize and view size for getEndHiddenViewSize, and setPreventZeroSizeViewSwipes

And the second question - what if i wanna disable item click while view is swiped?
I mean process main view click only in neutral position. I see only startSwipe callback. How to detect view in neutral position?

**Comment by alex-townsend** [comment]
If you want to only allow swiping open one side, your idea is correct to have the side that should not swipe return <side>HiddenViewSize() = 0 and use setPreventZeroSizeViewSwipes(true).

If you want to disable click events on an opened view, you can check the view's translationX (if you're swiping horizontally) or translationY (if you're swiping vertically) and if they're non-zero it means they have been swiped, so you do not act on the click event.

**Comment by alex-townsend** [comment]
Closing from inactivity.
