### ISSUE TITLE
SwipeOpenItemTouchHelper#closeAllOpenPositions method is no longer public with version 2.0.0.

### ISSUE THREAD

**Issue by tpiDev** [alex-townsend/SwipeOpenItemTouchHelper#45]
`SwipeOpenItemTouchHelper#closeAllOpenPositions` method is no longer public 
with version _2.0.0_. Is there any replacement for it?

**Comment by alex-townsend** [comment]
@tpiDev sorry about that -- I'll get it fixed with #46 and release a 2.0.1 today.

**Comment by tpiDev** [comment]
@alex-townsend Thank you!

**Comment by alex-townsend** [comment]
@tpiDev you should be able to pull down the 2.0.1 release now -- let me know if there are any issues.

**Comment by tpiDev** [comment]
Thanks again. Works fine. Closing issue.
